name: Insider UI Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        id: pytest
        run: |
          source .venv/bin/activate
          pytest tests/ --html=report.html --self-contained-html || echo "Tests failed"

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.html

      - name: Ensure screenshots directory exists
        run: |
          if [ ! -d "screenshots" ]; then
            echo "Screenshots directory not found. Creating empty directory."
            mkdir -p screenshots
          fi

      - name: Upload screenshots artifact
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/
